from __future__ import annotations

import os
import smtplib
from dataclasses import dataclass
from email.message import EmailMessage
from html import escape
from typing import Mapping


GMAIL_SENDER_ENV_VAR = "GMAIL_SENDER_EMAIL"
GMAIL_APP_PASSWORD_ENV_VAR = "GMAIL_APP_PASSWORD"
NEWSLETTER_RECIPIENT_ENV_VAR = "NEWSLETTER_RECIPIENT_EMAIL"
REQUIRED_EMAIL_ENV_VARS = (
    GMAIL_SENDER_ENV_VAR,
    GMAIL_APP_PASSWORD_ENV_VAR,
    NEWSLETTER_RECIPIENT_ENV_VAR,
)
TEST_EMAIL_SUBJECT = "Faculty Job Scout Test Email"


@dataclass(frozen=True)
class EmailResult:
    sent: bool
    detail: str


@dataclass(frozen=True)
class EmailCredentials:
    sender: str
    password: str
    recipient: str


class MissingEmailEnvironmentVariables(ValueError):
    def __init__(self, missing_names: list[str]) -> None:
        self.missing_names = tuple(missing_names)
        super().__init__(
            "Missing required email environment variables: " + ", ".join(self.missing_names)
        )


def load_email_credentials(
    environment: Mapping[str, str] | None = None,
) -> EmailCredentials:
    values = os.environ if environment is None else environment
    missing_names = [name for name in REQUIRED_EMAIL_ENV_VARS if not values.get(name, "").strip()]
    if missing_names:
        raise MissingEmailEnvironmentVariables(missing_names)
    return EmailCredentials(
        sender=values[GMAIL_SENDER_ENV_VAR].strip(),
        password=values[GMAIL_APP_PASSWORD_ENV_VAR],
        recipient=values[NEWSLETTER_RECIPIENT_ENV_VAR].strip(),
    )


def build_email_message(
    sender: str,
    recipient: str,
    subject: str,
    body: str,
    html_body: str | None = None,
) -> EmailMessage:
    message = EmailMessage()
    message["From"] = sender
    message["To"] = recipient
    message["Subject"] = subject
    message.set_content(body)
    message.add_alternative(html_body or render_email_html(body), subtype="html")
    return message


def render_email_html(body: str) -> str:
    """Render the digest's small Markdown subset as Gmail-friendly HTML."""
    content: list[str] = []
    card_open = False

    def close_card() -> None:
        nonlocal card_open
        if card_open:
            content.append("</div>")
            card_open = False

    for raw_line in body.splitlines():
        line = raw_line.rstrip()
        stripped = line.strip()
        if not stripped:
            close_card()
            continue
        if line.startswith("# "):
            close_card()
            content.append(
                '<h1 style="margin:0 0 20px;color:#16324f;font-size:28px;line-height:1.25">'
                f"{escape(line[2:])}</h1>"
            )
        elif line.startswith("## "):
            close_card()
            content.append(
                '<h2 style="margin:28px 0 12px;padding-bottom:7px;border-bottom:2px solid '
                '#dce6ef;color:#205b7a;font-size:20px;line-height:1.3">'
                f"{escape(line[3:])}</h2>"
            )
        elif line.startswith("- "):
            close_card()
            content.append(
                '<div style="margin:0 0 14px;padding:16px 18px;border:1px solid #dce6ef;'
                'border-radius:8px;background:#ffffff">'
                '<h3 style="margin:0 0 10px;color:#16324f;font-size:17px;line-height:1.35">'
                f"{escape(line[2:])}</h3>"
            )
            card_open = True
        elif line.startswith("  ") and card_open:
            label, separator, value = stripped.partition(":")
            rendered_value = _render_detail_value(label, value) if separator else escape(stripped)
            detail = (
                f"<strong>{escape(label)}:</strong> {rendered_value}"
                if separator
                else rendered_value
            )
            content.append(
                '<p style="margin:5px 0;color:#334e68;font-size:14px;line-height:1.45">'
                + detail
                + "</p>"
            )
        else:
            close_card()
            content.append(
                '<p style="margin:8px 0;color:#334e68;font-size:15px;line-height:1.55">'
                f"{escape(stripped)}</p>"
            )
    close_card()
    return (
        '<!doctype html><html><body style="margin:0;padding:0;background:#f4f7fa;">'
        '<div style="display:none;max-height:0;overflow:hidden">Faculty job matches and '
        "upcoming deadlines.</div>"
        '<main style="max-width:760px;margin:0 auto;padding:28px 20px;font-family:Arial,'
        'Helvetica,sans-serif">'
        + "".join(content)
        + '<p style="margin:28px 0 0;color:#829ab1;font-size:12px">Generated by Faculty '
        "Job Scout.</p></main></body></html>"
    )


def _render_detail_value(label: str, value: str) -> str:
    clean_value = value.strip()
    if label in {"Link", "Source"} and clean_value.startswith(("https://", "http://")):
        link_text = "Open job posting" if label == "Link" else "View source"
        return (
            f'<a href="{escape(clean_value, quote=True)}" '
            'style="color:#0b6e99;text-decoration:underline">'
            f"{link_text}</a>"
        )
    return escape(clean_value)


def send_email(
    sender: str,
    recipient: str,
    password: str,
    subject: str,
    body: str,
    smtp_host: str = "smtp.gmail.com",
    smtp_port: int = 587,
    use_tls: bool = True,
    dry_run: bool = False,
) -> EmailResult:
    if dry_run:
        return EmailResult(False, "Dry run: email was not sent.")
    message = build_email_message(sender, recipient, subject, body)
    with smtplib.SMTP(smtp_host, smtp_port, timeout=30) as smtp:
        if use_tls:
            smtp.starttls()
        smtp.login(sender, password)
        smtp.send_message(message)
    return EmailResult(True, f"Sent email to {recipient}.")
